---
galaxy_info:
  author: Steve Milner
  description: Deploy and Enable Atomic Multi-Host Manager
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
  - { role: os_firewall }
